go-admin-team/go-admin

- main.go
> graceful shutdown

- apis/tools/systables.go
- config/settings.yml
- middleware/auth.go
- models/tools/dbtables.go
- models/tools/systables.go
> V1.0.0 fixbug

- Dockerfile
- README.md
> 添加Dockerfile

- cmd/api/server.go
- config/db.sql
- global/adm.go
- jobs/examples.go
- jobs/jobbase.go
- models/gorm/gorm.go
- template/vue.go.template
1、升级代码生成模板
2、优化job加载方式
3、修复新增表结构初始化问题
4、其他问题的修复
> releases 1.1.4

- app/admin/service/dto/sys_content.go
> fix🐛 修复查询bug

- app/admin/apis/sys_user.go
- app/admin/router/sys_user.go
- config/db.sql
1.修正用户修改密码put接口url错误导致的无法修改密码问题
2.修正初始化SQL异常导致部分表无缺省参数问题
> bugfix:修正用户修改密码put接口url错误导致的无法修改密码问题,修正初始化SQL异常导致部分表无缺省参数问题

- app/admin/service/sys_user.go
- cmd/cobra.go
修复cobra未将app.StartCmd init导致创建App命令无效的问题以及修改基本资料由于object req无password导致用户密码为上一次密码hash值再次hash导致无法登录问题。
> fix:修复createapp未初始化导致无法创建app以及修改资本资料导致密码重复加密问题

- go.mod
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
> chore: upgrade gin to v1.7.3

- .github/workflows/go.yml
- go.mod
> fix :bug: gcc强依赖问题修复

- .github/workflows/go.yml
push docker to github packages example use actions.
> push docker

- README.Zh-cn.md
- app/admin/apis/sys_role.go
- app/admin/service/sys_role.go
- app/jobs/apis/sys_job.go
- app/jobs/service/sys_job.go
- common/global/adm.go
fix🐛: 添加roleKey验证(#649)
refactor🎨:   更新readme(#623)
> refactor🎨: 修复问题

- Dockerfile
bugfix: Fix Dockerfile to load config file
> Fix: Unable to load config file to Docker container

- README.Zh-cn.md
- README.md
The original url for cgo-issue was failed , I updated the new link.
> Fix readme cgo url

- app/admin/apis/sys_user.go
> fix UpdatePwd error

- app/admin/models/sys_menu.go
- app/admin/service/sys_menu.go
* **fix**:
1. 菜单展示问题
2. 菜单未排序(预期：与角色管理展示一致)
* **before**:
* **after**:
> fix🐛: fix rolemenu

- .gitignore
- Dockerfile
- Dockerfilebak
- Makefile
- docker-compose.yml
- restart.sh
- stop.sh
> 编写dockerfile启动脚本

- app/admin/apis/sys_config.go
- app/admin/models/sys_config.go
- app/admin/service/dto/sys_config.go
- cmd/migrate/migration/models/initdb.go
- common/middleware/handler/login.go
- config/pg.sql
https://github.com/go-admin-team/go-admin/issues/597
> 处理postgre启动报错问题

- .gitignore
- app/admin/models/sys_opera_log.go
- app/admin/service/dto/sys_opera_log.go
- cmd/migrate/migration/models/sys_opera_log.go
- common/middleware/logger.go
解决issues/705  ，修复日志创建时间筛选报错的bug
https://github.com/go-admin-team/go-admin/issues/705
1. 修复日志创建时间筛选报错的bug.
2. 修复日志里操作人，修改人，userAgent为空的bug.
3. 迁移表时，日志表添加字段注释.
4. sys_opera_log表oper_param字段类型改为text，解决字段长度报错的问题
[[中文版模板 / Chinese template](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |
⚠️ Please check all items below before review. ⚠️
> 1. 修复日志创建时间筛选报错的bug.

- README.Zh-cn.md
- README.md
Docs: update dependencies before build.
> Docs: update README

- app/admin/service/sys_config.go
[[中文版模板 / Chinese template](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
| 🇺🇸 English |           |
| 🇨🇳 Chinese |  refactor🎨:优化sys_config相关代码      |
⚠️ Please check all items below before review. ⚠️
> refactor🎨:优化sys_config相关代码

- app/admin/models/sys_role.go
- app/admin/service/dto/sys_role.go
- app/admin/service/sys_role.go
fix_edit_master_role模块添加注释
[[中文版模板 / Chinese template](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |
⚠️ Please check all items below before review. ⚠️
> fix_edit_master_role模块添加注释

- README.Zh-cn.md
- README.md
> fix setting.yml spelling

- docs/admin/admin_docs.go
- docs/admin/admin_swagger.json
- docs/admin/admin_swagger.yaml
- main.go
[[English Template / 英文模板](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE.md)]
| 语言    | 更新描述                                                     |
| ------- | ------------------------------------------------------------ |
| 🇺🇸 英文 | fix: Fix the go generate command not updating Swagger documentation |
| 🇨🇳 中文 | fix: 修复go generate命令不更新Swagger文档问题                |
⚠️ 请自检并全部**勾选全部选项**。⚠️
> fix: 修复go generate命令不更新Swagger文档问题

- template/v4/dto.go.template
- template/v4/model.go.template
[[中文版模板 / Chinese template](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |
⚠️ Please check all items below before review. ⚠️
> [fix](gen) ignore default time type columns in table

- common/middleware/logger.go
https://github.com/go-admin-team/go-admin/issues/810
| 🇺🇸 English | reset default logger fields |
| 🇨🇳 Chinese | 重置默认logger的fields字段 |
> fix🐛: reset default logger fields

- app/jobs/jobbase.go
[[English Template / 英文模板](https://github.com/go-admin-team/go-admin/blob/master/.github/PULL_REQUEST_TEMPLATE.md)]
- [√] 日常 bug 修复
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |          |
⚠️ 请自检并全部**勾选全部选项**。⚠️
- [√] 文档已补充或无须补充
- [√] 代码演示已提供或无须提供
- [√] TypeScript 定义已补充或无须补充
- [√] Changelog 已提供或无须提供
> fix:修复定时任务的日志打印

- template/v4/vue.go.template
自动生成的前端代码，点击编辑的时候不需要弹框确认，交互不友好
修改了自动生成代码的模板
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |          |
⚠️ 请自检并全部**勾选全部选项**。⚠️
> 点击编辑的时候不需要弹框确认，交互不太友好
